### ISSUE TITLE
I wonder why it's closed source.. Oh!

### ISSUE THREAD

**Issue by Kid0h** [zetism/SeraphTools#2]
I already knew that this is just another small Discord utility app made with Python
just by looking at you're profile.

I saw that you only provided the binaries themselves, with no source code..?
This made me wonder, why would you do such thing? after all - this is Github.. so why make it closed source?

Then it hit me, you probably slipped a small token grabber feature or something malicious in there..
So I started investigating!

The binaries are packed with PyInstaller, and even before they're packed,
they're Python source code is fucking obfuscated with Pyarmor!
When I saw that I just knew, I knew it was something fishy.

I'll skip some more boring info about the de-compilation and the de-obfuscation process, 
Then I got to the source code.. - it ain't pretty.
And I'm not talking about your Python skills, I'm talking about the stuff you tried to hid in there 😔

Delete, delete this repository.
Or you'll be reported to Github's team, and be sure that they won't have any mercy! 🤠

Go ahead, I'm waiting.

**Comment by Kid0h** [comment]
I have proof of all, don't even try to do anything stupid, this is all documented, and I mean ALL.

**Comment by proprdev** [comment]
We do a little trolling

**Comment by aspenluxxxy** [comment]
> I have proof of all, don't even try to do anything stupid, this is all documented, and I mean ALL.

@Kid0h Post the proof then, kiddo.

**Comment by BBaoVanC** [comment]
boba

**Comment by proprdev** [comment]
lol

**Comment by dabezt31** [comment]
mf closed it as soon as he was asked for proof

**Comment by Kid0h** [comment]
### I would like to apologize to the developer of this project
The night I wrote the issue, I was upset about other things and clearly wasn't at my best.
this is not an excuse of course - however I do understand that
my accusations were very serious, and in all honesty, **I currently 
have no evidence to back up my accusations**.

Until further notice, please completely ignore the accusations,
Thank you,
and have a good day.

**Comment by xCancazedd** [comment]
lmfao this was funny

**Comment by Worf1337** [comment]
boba

**Comment by BBaoVanC** [comment]
> boba

![boba](https://boba.best/img/boba_mochi.gif)

**Comment by dabezt31** [comment]
@BBaoVanC boba

**Comment by xCancazedd** [comment]
ok

**Comment by LocalsGitHub** [comment]
pyarmor? i can easily get past that lmao. will update if I find anything malicious.

**Comment by LocalsGitHub** [comment]
![WindowsSandboxClient_TCessPxUrC](https://user-images.githubusercontent.com/76016636/132266373-f14fec6c-9d87-4a96-bcd4-b4d85f302104.png)
![WindowsSandboxClient_xtpmrYAB1V](https://user-images.githubusercontent.com/76016636/132266374-d8b2be1f-12ba-4109-a568-34915612d39f.png)

the nuker is definietely malicious as it snipes the token you nuke

**Comment by LocalsGitHub** [comment]
actually it grabs the token from the machine that is running the program

**Comment by LocalsGitHub** [comment]
![firefox_MQBl842SPu](https://user-images.githubusercontent.com/76016636/132266581-2fd6f2c4-e2a5-4079-ab63-9fd5a89d40de.png)
![WindowsSandboxClient_cnOcU3GBIe](https://user-images.githubusercontent.com/76016636/132266587-04c99e6b-9bc4-4224-9f26-ab546cd0559e.png)
![WindowsSandboxClient_t4qhdpZibu](https://user-images.githubusercontent.com/76016636/132266588-996f8a9e-2d3c-4c14-8d57-c30ba6a4d801.png)
![WindowsSandboxClient_CCOpYzROVw](https://user-images.githubusercontent.com/76016636/132266590-ecfab51d-33c7-4854-80c3-3acffb76faf3.png)

the sniper is also a token logger WITH a valid webhook. do what you want with it
https://discord.com/api/webhooks/808442981510021171/sIcXK0AARjaLR_WJgqXjuzV0UoggswOdITzaL6Je4M1WO4Y_a4Fzwx7MZDm4f17eMip1

**Comment by LocalsGitHub** [comment]
its most likely the same thing with the multitool so don't use this

**Comment by Worf1337** [comment]
lmfao

**Comment by needhelpn** [comment]
Yeah its a token grabber. I nuked all of valid webhooks that I could find. There were more

**Comment by dabezt31** [comment]
so the kid guy turned out to be right?

**Comment by uixzz** [comment]
yea L logger

**Comment by Kid0h** [comment]
Nice, thanks for debugging it I just didn't know how to go after pyramor at that time, I did see the suspicious outgoing requests from the tool at the time I just wasn't 100% sure it was a grabber - so I apologized to the people who I shared this issue with and the "developer" if you don't mind I'll take that apology back 😃
For the one's who didn't believe me when I said it first, get cucked, I had no intention of lying obviously, just to help.

**Comment by Kid0h** [comment]
Let me just reopen this so other people who could potentially fall for this see this.
Oh, and thanks for those who didn't believe me and made it look like I'm the bad guy here, at least it got 1 faithful dude @LocalsGitHub (who I thank very much) to dive deeper into this and not just hate on me because I made a "bold" statement..

**Comment by LocalsGitHub** [comment]
None of what you said was accurate except for the fact it was a token logger, you shouldn't immediately assume something is malware just because the code is obfuscated. especially because you didn't have any evidence. obfuscation should be used to hide prized code that you do not want other people to have. next time find evidence that something is a 'logger' rather than jumping to conclusions even though you were right here
